### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [piotrmurach/equatable#4]
The "equatable" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

![Zrzut ekranu z 2019-06-21 10-30-17](https://user-images.githubusercontent.com/392754/59909278-97942700-940f-11e9-980b-4f3b5fd19213.png)

**Comment by piotrmurach** [comment]
Hey Maciej!

Thanks for bringing this to my attention.

The `equatable` gem has a license packaged together within the gem since its creation, please [see gemspec](https://github.com/piotrmurach/equatable/blob/master/equatable.gemspec#L25). It seems the software you're using checks only for the presence of `license` key in gemspec, which I think given this gem been created a long time ago, may not have been part of rubygems specification. So the license is present on github and distributed with the gem itself. However, I'm happy to add the license key to make it more compatible.

**Comment by mensfeld** [comment]
Since I bundle from rubygems: https://rubygems.org/gems/equatable

![Zrzut ekranu z 2019-06-23 18-21-52](https://user-images.githubusercontent.com/392754/59979128-d4187c00-95e3-11e9-89da-832c291090da.png)

**Comment by nijikon** [comment]
@piotrmurach you should provide the license in the gemspec file as well. https://guides.rubygems.org/specification-reference/#license=

If you could add it and release a new version that would be awesome.

**Comment by piotrmurach** [comment]
I've added [license](https://github.com/piotrmurach/equatable/commit/cb1d519dbd2a2c62642c02093170c63ea7840a26) name to gemspec.

The point I was trying to make is that the statement 
> The "equatable" gem seems not to have a license at all.

 is not true at all. The gem always had a license packaged with it. Software that comes with a license file has a license. There are many ways to use the gem outside of rubygems website. It can be downloaded as `zip` or `tar.gz` from GitHub. Many of my gems are repackaged by different Linux distributions which do care about licensing.

The `license` key has been added to gemspec in recent years so there are many gems that do have license file but do not include a license key in their gemspec. For example [unicode_utils](https://rubygems.org/gems/unicode_utils) gem. Is the quality tool going to say they are unlicensed?

A further problem with this approach is that even most used gems older versions won't have the `license` key either. For example [rake](https://rubygems.org/gems/rake/versions/0.9.6) utility. I mean, if someone will have an old version of rake as part of their project, is the quality checking tool also going to say it doesn't have a license at all? 

![Screen Shot 2019-06-26 at 20 58 34](https://user-images.githubusercontent.com/444312/60207762-f6fe9680-9856-11e9-9e71-d89397d6dae0.png)

**Comment by mensfeld** [comment]
> if someone will have an old version of rake as part of their project, is the quality checking tool also going to say it doesn't have a license at all?

Yes. That is a fair point that should be included in our quality tools evaluations (although it's a bit more tricky it is doable @nijikon). I guess what would be good here, is to scan all gems at rubygems and update the licenses according to the licenses presented inside if they are present. @hsbt - did you consider something like that for rubygems?

**Comment by piotrmurach** [comment]
Released `v0.6.1` with a `license` key so it should satisfy the tool now.

**Comment by mensfeld** [comment]
Thank you @piotrmurach <3 you're the man!
